### ISSUE TITLE
readSessionsList: Session StringField title does not exist.

### ISSUE THREAD

**Issue by yayachang** [android/health-samples#14]
When I generate a running exercise from Samsung Galaxy 4 watch then sync to Samsung health app.
(I had installed Health Platform).
Then run the health-samples，it crashes at HealthPlatformManager.kt(line 118).
java.lang.IllegalArgumentException: StringField title does not exist.

The following is the log:
com.example.healthplatformsample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.healthplatformsample, PID: 24891
    **java.lang.IllegalArgumentException: StringField title does not exist**
        at com.google.android.libraries.healthdata.data.DataValueHelper.zzp(com.google.android.libraries.healthdata:health-data-api@@1.0.0-alpha01:2)
        at com.google.android.libraries.healthdata.data.IntervalData.getStringValue(com.google.android.libraries.healthdata:health-data-api@@1.0.0-alpha01:3)
        at com.example.healthplatformsample.data.HealthPlatformManager.readSessionsList(HealthPlatformManager.kt:118)
        at com.example.healthplatformsample.data.HealthPlatformManager$readSessionsList$1.invokeSuspend(Unknown Source:14)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by garanj** [comment]
Should be fixed in PR #17
