### ISSUE TITLE
PassiveData - StartupReceiver doesn't initiate registerForHeartRateData

### ISSUE THREAD

**Issue by amoledwatchfaces** [android/health-samples#20]
@garanj 

StartupReceiver doesn't initiate registerForHeartRateData.

Tested with - 
adb root 
adb shell
am broadcast -a android.intent.action.BOOT_COMPLETED -p com.example.passivedata

When restarting watch, BOOT_COMPLETED does not trigger register for background data

This error happens
```
2022-05-06 12:04:21.718 1697-1697/com.example.passivedata I/Passive Data Sample: Enqueuing worker
2022-05-06 12:04:21.759 1697-1738/com.example.passivedata E/WM-WorkerFactory: Could not instantiate com.example.passivedata.RegisterForBackgroundDataWorker
    java.lang.NoSuchMethodException: com.example.passivedata.RegisterForBackgroundDataWorker.<init> [class android.content.Context, class androidx.work.WorkerParameters]
        at java.lang.Class.getConstructor0(Class.java:2332)
        at java.lang.Class.getDeclaredConstructor(Class.java:2170)
        at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:95)
        at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:244)
        at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:136)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2022-05-06 12:04:21.759 1697-1738/com.example.passivedata E/WM-WorkerWrapper: Could not create Worker com.example.passivedata.RegisterForBackgroundDataWorker
```

We should see >>>  I/Passive Data Sample: Registering for background data.

**Comment by garanj** [comment]
Thanks. I can replicate this. Will take a look.

**Comment by garanj** [comment]
@amoledwatchfaces Are you able to confirm whether the update just patched in works in fixing the issue for you?

**Comment by amoledwatchfaces** [comment]
@garanj I can confirm that with AndroidManifest.xml change, it's successfully initiate worker (worker running + registering for background data) but there is new set of errors.

```
2022-05-06 12:17:18.998 3005-3209/com.example.passivedata I/Passive Data Sample: Registering for background data.
2022-05-06 12:17:19.006 449-2820/system_process W/ActivityManager: **Unable to start service Intent { act=hs.versionclient.BIND pkg=com.example.passivedata } U=0: not found**

2022-05-06 12:17:19.006 1713-16503/com.google.android.wearable.healthservices E/ServiceConnection: Connection to service is not available for package 'com.example.passivedata' and action 'hs.versionclient.BIND'.

2022-05-06 12:17:19.007 1713-3139/com.google.android.wearable.healthservices W/WHS_IpcBackedSdkVersionManager: Failed to fetch version for packageName=com.example.passivedata
    java.util.concurrent.ExecutionException: java.util.concurrent.CancellationException: Service not available
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(PG:4)
        at com.google.common.util.concurrent.AbstractFuture.get(PG:30)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(PG:2)
        at com.google.android.wearable.healthservices.common.versioning.IpcBackedSdkVersionManager.lambda$logSdkVersionForPackage$0$com-google-android-wearable-healthservices-common-versioning-IpcBackedSdkVersionManager(PG:3)
        at com.google.android.wearable.healthservices.common.versioning.IpcBackedSdkVersionManager$$ExternalSyntheticLambda0.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.util.concurrent.CancellationException: Service not available
        at androidx.health.services.client.impl.ipc.internal.ServiceConnection.connect(PG:11)
        at androidx.health.services.client.impl.ipc.internal.ServiceConnection.enqueue(PG:4)
        at androidx.health.services.client.impl.ipc.internal.ConnectionManager.handleMessage(PG:13)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
		
2022-05-06 12:17:19.010 1713-16503/com.google.android.wearable.healthservices E/ServiceConnection: Connection disconnected and maximum number of retries reached.
    java.util.concurrent.CancellationException: Service not available
        at androidx.health.services.client.impl.ipc.internal.ServiceConnection.connect(PG:11)
        at androidx.health.services.client.impl.ipc.internal.ServiceConnection.enqueue(PG:4)
        at androidx.health.services.client.impl.ipc.internal.ConnectionManager.handleMessage(PG:13)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
		
2022-05-06 12:17:19.019 3005-3143/com.example.passivedata I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=c9a5566b-3e69-4b97-ba71-c8be4555e0bb, tags={ com.example.passivedata.RegisterForBackgroundDataWorker } ]
```
