### ISSUE TITLE
NullPointerException in PassiveData and PassiveEvents sample projects.

### ISSUE THREAD

**Issue by AlexandraFilyakova** [android/health-samples#3]
I faced the next NullPointerException when I try to do "Enable" Passive Data or Passive Events on emulator Wear OS API 30:

```
java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.google.common.util.concurrent.ListenableFuture.cancel(boolean)' on a null object reference
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2392)
        at android.os.Parcel.createException(Parcel.java:2370)
        at android.os.Parcel.readException(Parcel.java:2353)
        at android.os.Parcel.readException(Parcel.java:2295)
        at androidx.health.services.client.impl.IPassiveMonitoringApiService$Stub$Proxy.registerDataCallback(IPassiveMonitoringApiService.java:318)
        at androidx.health.services.client.impl.ServiceBackedPassiveMonitoringClient$registerDataCallbackInternal$serviceOperation$1.execute(ServiceBackedPassiveMonitoringClient.kt:122)
        at androidx.health.services.client.impl.ipc.Client$3.execute(Client.java:222)
        at androidx.health.services.client.impl.ipc.internal.ServiceConnection.execute(ServiceConnection.java:243)
        at androidx.health.services.client.impl.ipc.internal.ServiceConnection.enqueue(ServiceConnection.java:200)
        at androidx.health.services.client.impl.ipc.internal.ConnectionManager.handleMessage(ConnectionManager.java:123)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by yingding** [comment]
yeah, i trace back to the HealthServicesManager#registerForHeartRateData call. It raise Exception at
```kotlin
     passiveMonitoringClient.registerDataCallback(dataTypes, pendingIntent)
```
The registerDataCallback just dies.

**Comment by yingding** [comment]
I just upgrade Wear OS 3 Preview API 30 Image to Revision 4 from Beta Channel. Recreated a new AVD, and manually added `hw.sensors.heart_rate = yes` in config.ini of the new Wear OS 3 AVD before the first start. Now the health services seems to work again.

**Comment by garanj** [comment]
Going to close this one out for now - if the issue remains with `alpha02`, can reopen.

**Comment by cancan101** [comment]
Not sure if this is the same issue but am seeing similar exceptions on Wear OS 4 using the PassiveDataCompose app. I did modify it to report user activity:
```
Process: com.example.passivedatacompose, PID: 7825
java.lang.RuntimeException: Unable to create service com.example.passivedatacompose.service.PassiveDataService: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4528)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2162)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
	at android.content.ContextWrapper.getApplicationContext(ContextWrapper.java:146)
	at androidx.datastore.preferences.PreferenceDataStoreSingletonDelegate.getValue(PreferenceDataStoreDelegate.kt:100)
	at androidx.datastore.preferences.PreferenceDataStoreSingletonDelegate.getValue(PreferenceDataStoreDelegate.kt:78)
	at com.example.passivedatacompose.data.PassiveDataRepositoryKt.getDataStore(PassiveDataRepository.kt:28)
	at com.example.passivedatacompose.data.PassiveDataRepositoryKt.access$getDataStore(PassiveDataRepository.kt:1)
	at com.example.passivedatacompose.data.PassiveDataRepository.<init>(PassiveDataRepository.kt:31)
	at com.example.passivedatacompose.service.PassiveDataService.<init>(PassiveDataService.kt:35)
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:75)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4497)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2162) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:201) 
	at android.os.Looper.loop(Looper.java:288) 
	at android.app.ActivityThread.main(ActivityThread.java:7898) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
