### ISSUE TITLE
When i click the session the app is crash

### ISSUE THREAD

**Issue by kelfin91** [android/health-samples#53]
Process: com.example.healthconnectsample, PID: 6832
                                                                                                    java.lang.IllegalStateException: Null binding
                                                                                                    	at androidx.health.platform.client.impl.ipc.internal.ServiceConnection.onNullBinding(ServiceConnection.java:374)
                                                                                                    	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2080)
                                                                                                    	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2110)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7842)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@66bf534, Dispatchers.Main.immediate]

**Comment by breanatate** [comment]
Hello,

Do you have a screen lock for your device? Without a screen lock, the device does not support the Health Connect service binding.
