### ISSUE TITLE
Exercise Sample App Crashes when opened - exerciseClient.capabilities returns null 

### ISSUE THREAD

**Issue by ZammitMelvin** [android/health-samples#6]
The Exercise Sample App crashes immediately when run with the following error:

```
Process: com.example.exercise,
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Set androidx.health.services.client.data.ExerciseCapabilities.getSupportedExerciseTypes()' on a null object reference
        at com.example.exercise.HealthServicesManager.getExerciseCapabilities(HealthServicesManager.kt:57)
        at com.example.exercise.HealthServicesManager$getExerciseCapabilities$1.invokeSuspend(Unknown Source:11)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:227)
        at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:362)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:396)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:388)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:293)
        at androidx.concurrent.futures.ToContinuation.run(ListenableFuture.kt:80)
        at androidx.concurrent.futures.DirectExecutor.execute(DirectExecutor.java:35)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1215)
        at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:983)
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:746)
        at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.setResult(AbstractTransformFuture.java:248)
        at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:163)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:7690)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
```

The issue is HealthServicesManager.kt line 57, the reason being that the exerciseClient is returning null capabilities:

```
suspend fun getExerciseCapabilities(): ExerciseTypeCapabilities? {
if (!capablitiesLoaded) {
   val capabilities = exerciseClient.capabilities.await()
   if (ExerciseType.RUNNING in capabilities.supportedExerciseTypes) {
      exerciseCapabilities = capabilities.getExerciseTypeCapabilities(ExerciseType.RUNNING)
   }
   capablitiesLoaded = true
   }
   return exerciseCapabilities
}
```

Internally, the Google Health services API is having this error:

```
E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
    bad: Protocol message contained an invalid tag (zero).
        at ahy.A(PG:1)
        at ahy.A(PG:4)
        at bbb.c(PG:59)
        at bbb.i(PG:2)
        at azo.parsePartialFrom(PG:21)
        at azo.parseFrom(PG:24)
        at androidx.health.services.client.proto.RequestsProto$CapabilitiesRequest.parseFrom(PG:9)
        at androidx.health.services.client.impl.request.CapabilitiesRequest$$special$$inlined$newCreator$1.createFromParcel(PG:2)
        at androidx.health.services.client.impl.request.CapabilitiesRequest$$special$$inlined$newCreator$1.createFromParcel(PG:4)
        at qb.a(PG:2)
        at androidx.health.services.client.impl.IExerciseApiService$Stub.dispatchTransaction(PG:13)
        at qa.onTransact(PG:2)
        at android.os.Binder.execTransactInternal(Binder.java:1154)
        at android.os.Binder.execTransact(Binder.java:1123)
```

**Comment by garanj** [comment]
Going to close this one out for now - if the issue remains with `alpha02`, can reopen.
