### ISSUE TITLE
PassiveData - minifyEnabled true - app crashes

### ISSUE THREAD

**Issue by amoledwatchfaces** [android/health-samples#62]
Is there any way we can prevent app crashes when minifyEnabled is set to true?
Is there any guide to health services regarding proguard-rules?
```
buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
```

**Comment by garanj** [comment]
Can you share an example crash?

**Comment by amoledwatchfaces** [comment]
Hi, it's not possible to share crash as I believe it's not possible to debug app with minifyEnabled set to true.
This is how the crash looks like:
https://drive.google.com/file/d/1GnpZaVl9TstrkCXsxFbpwmX1n6x5ngdW/view?usp=sharing

I've also tried debugging build by adding 
```
-dontobfuscate
-keepattributes SourceFile,LineNumberTable
```
to proguard-rules.pro and useProguard false in the debug
```
debug {
    minifyEnabled true
    useProguard false
    proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
}
```
but this throws "No signature of method: build_1hzrb38iw9ctad0f5ig6u8re0.android()" because "useProguard" is not working anymore and without it, debug build will not be minified.

You can test this crash by building release with minifyEnabled true, then adb install app-release.apk.
App will not work. Looks like Health Services or some other project part needs proper Progard rules set.

**Comment by garanj** [comment]
I can replicate crashes with release mode.

If you're connected up to adb when using your release build you should still be able to see stacktrace from the crash. If you're able to share that would be helpful.

I'll update this when we've more info on a fix.

**Comment by amoledwatchfaces** [comment]
Here it is, but I don't know if it helps because of obfuscation
```
2022-11-02 14:22:39.294  5337-5337  AndroidRuntime          pid-5337                             

E  FATAL EXCEPTION: main
                Process: com.example.passivedata, PID: 5337
                java.lang.ExceptionInInitializerError
                	at o2.h.<init>(Unknown Source:14)
                	at o2.g$a.get(Unknown Source:20)
                	at androidx.lifecycle.a.b(Unknown Source:60)
                	at b4.d.b(Unknown Source:14)
                	at androidx.lifecycle.o0.b(Unknown Source:68)
                	at androidx.lifecycle.o0.a(Unknown Source:23)
                	at androidx.lifecycle.m0.a(Unknown Source:51)
                	at com.example.passivedata.MainActivity.D(Unknown Source:2)
                	at com.example.passivedata.MainActivity$a.p(Unknown Source:28)
                	at k4.a.i(Unknown Source:7)
                	at y4.g0.run(Unknown Source:100)
                	at androidx.lifecycle.e.a(Unknown Source:43)
                	at androidx.lifecycle.k.a(Unknown Source:65)
                	at androidx.lifecycle.s$a.a(Unknown Source:17)
                	at androidx.lifecycle.s.h(Unknown Source:331)
                	at androidx.lifecycle.s.g(Unknown Source:49)
                	at androidx.lifecycle.s.f(Unknown Source:9)
                	at androidx.lifecycle.c0.a(Unknown Source:28)
                	at androidx.lifecycle.c0$a.onActivityPostStarted(Unknown Source:2)
                	at android.app.Activity.dispatchActivityPostStarted(Activity.java:1365)
                	at android.app.Activity.performStart(Activity.java:8095)
                	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3482)
                	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
                	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
                	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
                	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2073)
                	at android.os.Handler.dispatchMessage(Handler.java:106)
                	at android.os.Looper.loop(Looper.java:246)
                	at android.app.ActivityThread.main(ActivityThread.java:7690)
                	at java.lang.reflect.Method.invoke(Native Method)
                	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
                	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
                	Suppressed: t0.h1: [i1{Cancelling}@b870d7f, Dispatchers.Main.immediate]
                Caused by: java.lang.RuntimeException: Field name_ for f1.e not found. Known fields are [public java.lang.String f1.e.g, public int f1.e.h, public int f1.e.i, public static final f1.e f1.e.j, public static volatile w3.v$b f1.e.k]
                	at w3.r0.D(Unknown Source:72)
                	at w3.r0.v(Unknown Source:689)
                	at w3.x0.a(Unknown Source:194)
                	at w3.v$a.j(Unknown Source:21)
                	at w3.v$a.i(Unknown Source:0)
                	at x0.e.<init>(Unknown Source:174)
                	at x0.g.<init>(Unknown Source:6)
                	at x0.e.<clinit>(Unknown Source:10)
                	... 33 more
```

**Comment by Gawdl3y** [comment]
Having the same issue with my project using Health Services. It started occurring upon adding Health Services as a dependency and implementing the MeasureClient code, but only when minification is enabled. Here's a retraced stack:
```
java.lang.ExceptionInInitializerError
        at com.gawdl3y.android.hrmws.HealthServicesManager$heartRateMeasureFlow$1.invokeSuspend(HealthServicesManager.java:0)
        at com.gawdl3y.android.hrmws.HealthServicesManager$heartRateMeasureFlow$1.invoke(HealthServicesManager.java:0)
        at com.gawdl3y.android.hrmws.HealthServicesManager$heartRateMeasureFlow$1.invoke(HealthServicesManager.java:0)
        at kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo$suspendImpl(ChannelFlowBuilder.java:0)
        at kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo(ChannelFlowBuilder.java:0)
        at kotlinx.coroutines.flow.CallbackFlowBuilder.collectTo(CallbackFlowBuilder.java:0)
        at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.java:32)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:7)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:100)
        at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.java:0)
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:0)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:0)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:0)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.java:0)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.java:0)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(BuildersKt__Builders_common.kt:0)
        at kotlinx.coroutines.BuildersKt.launch(Builders.kt:0)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(BuildersKt__Builders_common.kt:0)
        at kotlinx.coroutines.BuildersKt.launch$default(Builders.kt:0)
        at com.gawdl3y.android.hrmws.WebSocketService.connect(WebSocketService.java:0)
        at com.gawdl3y.android.hrmws.WebSocketService$connect$1.invokeSuspend(WebSocketService.java:11)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:7)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:100)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.java:0)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.java:0)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.java:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
        Suppressed: androidx.datastore.preferences.protobuf.UninitializedMessageException: [m1{Cancelling}@ed0263c, Dispatchers.Main.immediate]
Caused by: java.lang.RuntimeException: Field name_ for u2.e0 not found. Known fields are [public java.lang.String u2.e0.e, public int u2.e0.f, public int u2.e0.g, public static final u2.e0 u2.e0.h, public static volatile z3.y u2.e0.i]
        at com.google.protobuf.MessageSchema.reflectField(MessageSchema.java:72)
        at com.google.protobuf.MessageSchema.newSchemaForRawMessageInfo(MessageSchema.java:689)
        at com.google.protobuf.MessageSchema.newSchema(MessageSchema.java:0)
        at com.google.protobuf.ManifestSchemaFactory.newSchema(ManifestSchemaFactory.java:0)
        at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:0)
        at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:0)
        at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:0)
        at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:0)
        at com.google.protobuf.GeneratedMessageLite$Builder.buildPartial(GeneratedMessageLite.java:0)
        at com.google.protobuf.GeneratedMessageLite$Builder.a(GeneratedMessageLite.java:0)
        at androidx.health.services.client.data.DataType.<init>(DataType.java:0)
        at androidx.health.services.client.data.DeltaDataType.<init>(DeltaDataType.java:6)
        at androidx.health.services.client.data.DataType.<clinit>(DataType.java:0)
        ... 24 more
```

**Comment by garanj** [comment]
Thanks for this additional comment - working on getting this investigated.

**Comment by Gawdl3y** [comment]
Thanks, good to hear! Quick correction: it turns out that changing `minifyEnabled` to `false` actually doesn't avoid the issue in my case, so it might be something else about R8 or the default release config.

**Comment by garanj** [comment]
As a workaround, you can add the rules to your proguard configuration, e.g. `proguard-rules.pro`:

In my case the crash was:

```
Caused by: java.lang.RuntimeException: Field name_ for r3.h not found. Known fields are [public java.lang.String r3.h.m, public int r3.h.n, public int r3.h.o, public static final r3.h r3.h.p, public static volatile u8.v$b r3.h.q]
                                                                                                    	at u8.r0.D(Unknown Source:72)
```

Looking in:

`build/outputs/mapping/release/mapping.txt`

and searching for the obfuscated name, `r3.h` in my case I find:

```
androidx.health.services.client.proto.DataProto$DataType -> r3.h:
```

Adding the following rules to my `proguard-rules.pro` then fixes the issue:

```
-keep class androidx.health.services.client.proto.** { *; }
-keepnames class androidx.health.services.client.proto.** { *; }
```

I would be interested to know which obfuscated names are causing the crashes in both cases @Gawdl3y @amoledwatchfaces

**Comment by amoledwatchfaces** [comment]
Thanks for this!
For me it was:
`androidx.health.services.client.proto.DataProto$DataType -> k1.e:`

**Comment by garanj** [comment]
As @yschimke has pointed out, a better solution is : 

```
-keep class * extends com.google.protobuf.GeneratedMessageLite { *; }
```

Which I've just tried and works for me - does this also work for you @amoledwatchfaces ?

See: https://chromium.googlesource.com/external/github.com/google/protobuf/+/HEAD/java/lite.md#r8-rule-to-make-production-app-builds-work

We'll look at how we can update the samples, and ideally move this into Health Services itself.

**Comment by amoledwatchfaces** [comment]
Works too! 👍

**Comment by garanj** [comment]
Thanks for confirming, much appreciated.
