### ISSUE TITLE
Exercise Sample - WCS SDK Client 'HealthServicesExerciseClient' disconnected in Wear OS 3.5

### ISSUE THREAD

**Issue by hoavutomosia** [android/health-samples#67]
I tried running the project in wear os 3.5 but got the problem, please check it.
`WCS SDK Client 'HealthServicesExerciseClient' disconnected, retrying connection. Retry attempt: 0
                                                                                                    java.util.concurrent.CancellationException
                                                                                                    	at androidx.health.services.client.impl.ipc.internal.ServiceConnection.lambda$cleanOnDeath$0$androidx-health-services-client-impl-ipc-internal-ServiceConnection(ServiceConnection.java:308)
                                                                                                    	at androidx.health.services.client.impl.ipc.internal.ServiceConnection$$ExternalSyntheticLambda0.binderDied(Unknown Source:2)
                                                                                                    	at android.os.IBinder$DeathRecipient.binderDied(IBinder.java:305)
                                                                                                    	at android.os.BinderProxy.sendDeathNotice(BinderProxy.java:685)`

**Comment by ithinkihaveacat** [comment]
@hoavutomosia I can't reproduce this. What device are you using? What Health Services version do you have?

```sh
$ adb shell dumpsys package com.google.android.wearable.healthservices | grep -E "versionCode|versionName"
    versionCode=189691 minSdk=30 targetSdk=30
    versionName=0.15.29.492301790
    versionCode=77257 minSdk=30 targetSdk=30
    versionName=0.8.30.449110343
```

(The "lower" version codes will be of the system-installed Health Service app; the "higher" ones are from the Play Store-installed update.)

**Comment by nogavicka** [comment]
I see the same error on Wear OS Emulator Small Round API 30.

```
D/ServiceConnection: onServiceDisconnected(), componentName = ComponentInfo{com.google.android.wearable.healthservices/com.google.android.wearable.healthservices.passivemonitoring.client.PassiveMonitoringApiService}
E/ServiceConnection: Binding died for client 'HealthServicesPassiveMonitoringClient'.
W/ServiceConnection: Connection is already re-established. No need to reconnect again
E/ServiceConnection: Cannot bind client 'HealthServicesPassiveMonitoringClient', binder is null
W/ServiceConnection: Connection is already re-established. No need to reconnect again
W/ServiceConnection: Binder died for client:HealthServicesPassiveMonitoringClient

W/ServiceConnection: WCS SDK Client 'HealthServicesPassiveMonitoringClient' disconnected, retrying connection. Retry attempt: 0
    java.util.concurrent.CancellationException
        at androidx.health.services.client.impl.ipc.internal.ServiceConnection.lambda$cleanOnDeath$0$androidx-health-services-client-impl-ipc-internal-ServiceConnection(ServiceConnection.java:308)
        at androidx.health.services.client.impl.ipc.internal.ServiceConnection$$ExternalSyntheticLambda0.binderDied(Unknown Source:2)
        at android.os.IBinder$DeathRecipient.binderDied(IBinder.java:305)
        at android.os.BinderProxy.sendDeathNotice(BinderProxy.java:685)
```

**Comment by ithinkihaveacat** [comment]
@nogavicka Can you share your Health Services version? See the adb code at https://github.com/android/health-samples/issues/67#issuecomment-1375493306.

**Comment by nogavicka** [comment]
```
    adb shell dumpsys package com.google.android.wearable.healthservices | grep -E "versionCode|versionName"
    versionCode=70695 minSdk=30 targetSdk=30
    versionName=0.8.16.446506339
```

**Comment by ithinkihaveacat** [comment]
@nogavicka Pretty sure you just need to update your Health Services version, can you trying following these loose instructions https://github.com/android/health-samples/issues/51#issuecomment-1412981600?
